export const TEST_QUIZ_EVENTS = {
  GS: {
    _: 'GS',
  },
  GE: {
    _: 'GE',
  },
  CQ: {
    _sT: 1538047009000,
    _eT: 1538047069000,
    _: 'CQ',
    _p: 'Yuvraj Singh and Vidya Balan',
    eId: 'e-nHb87iiFX',
    eNo: 'EP52 ',
    dT: '2018-09-27T11:16:26.000Z',
    ll: [],
    bT: '2018-09-27T11:17:54.000Z',
    nQT: '2018-09-27T11:30:57.000Z',
    dV: '320',
    qId: 'q-X-_FKSvOze',
    qT: 'Which company is the subject of the book \'Kingdom of the Soap Queen\' written by Kovid Gupta ?',
    as: {'a': 'A.Nirma', 'b': 'B.Balaji Telefilms', 'c': 'C.Dharma Productions', 'd': 'D.Godrej Consumer Products'},
    qTH: 'कोविद गुप्ता द्वारा लिखी गई पुस्तक \'किंगडम ऑफ़ द सोप क्वीन\' की विषय - वस्तु कौनसी कंपनी है ?',
    aH: { 'a':  'A.निरमा', 'b': 'B.बालाजी टेलीफ़िल्म्स', 'c': 'C.धर्मा प्रोडक्शंस', 'd': 'D.गोदरेज कंस्यूमर प्रोडक्ट्स'},
    aurl: '',
    vurl: '',
    playing_users_count: 3,
    _id: '4gTcqU4RM'
  },
  CQD: {
    _sT: 1538047009000,
    _eT: 1538047069000,
    _: 'CQD',
    _p: 'Yuvraj Singh and Vidya Balan',
    eId: 'e-nHb87iiFX',
    eNo: 'EP52 ',
    dT: '2018-09-27T11:16:26.000Z',
    ll: [],
    bT: '2018-09-27T11:17:54.000Z',
    nQT: '2018-09-27T11:30:57.000Z',
    dV: '320',
    qId: 'q-X-_FKSvOze',
    qT: 'Which company is the subject of the book \'Kingdom of the Soap Queen\' written by Kovid Gupta ?',
    as: {'a': 'A.Nirma', 'b': 'B.Balaji Telefilms', 'c': 'C.Dharma Productions', 'd': 'D.Godrej Consumer Products'},
    qTH: 'कोविद गुप्ता द्वारा लिखी गई पुस्तक \'किंगडम ऑफ़ द सोप क्वीन\' की विषय - वस्तु कौनसी कंपनी है ?',
    aH: { 'a':  'A.निरमा', 'b': 'B.बालाजी टेलीफ़िल्म्स', 'c': 'C.धर्मा प्रोडक्शंस', 'd': 'D.गोदरेज कंस्यूमर प्रोडक्ट्स'},
    aurl: '',
    vurl: '',
    playing_users_count: 3,
    _id: '4gTcqU4RM'
  },
  CAT: {
    _sT: 1538047009000,
    _eT: 1538047069000,
    _: 'CAT',
    _p: 'Yuvraj Singh and Vidya Balan',
    eId: 'e-nHb87iiFX',
    eNo: 'EP52 ',
    dT: '2018-09-27T11:16:26.000Z',
    ll: [],
    bT: '2018-09-27T11:17:54.000Z',
    nQT: '2018-09-27T11:30:57.000Z',
    dV: '320',
    qId: 'q-X-_FKSvOze',
    qT: 'Which company is the subject of the book \'Kingdom of the Soap Queen\' written by Kovid Gupta ?',
    as: {'a': 'A.Nirma', 'b': 'B.Balaji Telefilms', 'c': 'C.Dharma Productions', 'd': 'D.Godrej Consumer Products'},
    qTH: 'कोविद गुप्ता द्वारा लिखी गई पुस्तक \'किंगडम ऑफ़ द सोप क्वीन\' की विषय - वस्तु कौनसी कंपनी है ?',
    aH: { 'a':  'A.निरमा', 'b': 'B.बालाजी टेलीफ़िल्म्स', 'c': 'C.धर्मा प्रोडक्शंस', 'd': 'D.गोदरेज कंस्यूमर प्रोडक्ट्स'},
    aurl: '',
    vurl: '',
    playing_users_count: 3,
    _id: '4gTcqU4RM',
    _a: 'b'
  }
};

export const GAME_STATES = {
  NOT_STARTED: 0,
  WAIT_FOR_NEXT_QUESTION: 1,
  SHOW_QUESTION: 2,
  SHOW_OPTIONS: 3,
  CORRECT_ANSWER: 4,
  WRONG_ANSWER: 5,
  NOT_ANSWERED: 6,
  FINISHED: 7
};
